### ISSUE TITLE
ec2_bash missing?

### ISSUE THREAD

**Issue by henryk-modzelewski** [samoconnor/AWSLambda.jl#10]
running `create_jl_lambda_base(aws)` generates en error:

ERROR: UndefVarError: ec2_bash not defined
 in #create_jl_lambda_base#52(::String, ::Void, ::Function, ::Dict{Symbol,Any}) at /Volumes/Homes/henryk/.julia/v0.5/AWSLambda/src/AWSLambda.jl:1044
 in create_jl_lambda_base(::Dict{Symbol,Any}) at /Volumes/Homes/henryk/.julia/v0.5/AWSLambda/src/AWSLambda.jl:812

**Comment by samoconnor** [comment]
Hi @henryk-modzelewski,

Sorry for the long delay.

`ec2_bash` was on the un-tagged `master` branch of `AWSEC2.jl`. It is now tagged: https://github.com/samoconnor/AWSEC2.jl/releases/tag/v0.0.8
