### ISSUE TITLE
Custom linux packages

### ISSUE THREAD

**Issue by rob-luke** [samoconnor/AWSLambda.jl#4]
Currently you have [manually specified](https://github.com/samoconnor/AWSLambda.jl/blob/master/src/AWSLambda.jl#L1018) the amazon linux packages to load. Would it be possible to optionally specify these? Perhaps using a similar syntax to the lambda packages? Something like: 

``` julia
aws[:linux_packages] = ["git", "cmake", ... , "python27-devel"] 
```

I suggest this because I would like to use PyCall and PyPlot in my lambda function. Currently I am modifying the local version of AWSLambda.jl.

Thanks for the great package!

**Comment by samoconnor** [comment]
Try this: https://github.com/samoconnor/AWSLambda.jl/commit/a1fa561c6f6f1c6606acb0ec88e1dbfc5edc7a3b

``` Julia
aws[:lambda_yum_packages] = ["python27-devel"]
```

_Available package list: https://aws.amazon.com/amazon-linux-ami/2015.09-packages/ ._

In my production setup I have:

``` julia
aws[:lambda_base] = "custom_lambda_base.zip"

merge_lambda_zip(aws, "custom_lambda_base.zip",
                      "jl_lambda_base.zip", ["custom_libs.zip"])
```

Setting `:lambda_base` causes `create_jl_lambda` to use the specified ZIP in place of `"jl_lambda_base.zip`.

**Comment by rob-luke** [comment]
Thanks for your help
